@startuml
|PL (AGI)|
:Phasenübergang
bei AG beantragen;
:Kickoff-Meetings
durchfüren;
|AG (Fachamt)|
:Projekt freigeben;
:ruhend.../
|PL (AGI)|
:konzept}
:Konzept AP's
erarbeiten (lassen);
:PMP für
Realisierung
erarbeiten;
:Phasenübergang
bei AG beantragen;
|AG (Fachamt)|
:Realisierung
freigeben;
|PL (AGI)|
:realisierung}
:Realisierung's AP's
erarbeiten (lassen);
:PMP für
Einführung
erarbeiten;
:Phasenübergang
bei AG beantragen;
|AG (Fachamt)|
:Einführung
freigeben;
|PL (AGI)|
:einführung}
:Einführungs's AP's
erarbeiten (lassen);
:PMP für
Projektabschluss
erarbeiten;
:Projektabschluss
bei AG beantragen;
|AG (Fachamt)|
:Projektabschluss
bewilligen;
|PL (AGI)|
:abgeschlossen}
end
@enduml