@startuml
|Mitarbeiter A|
start
:Ticket eröffnen;
:entwurf}
|Mitarbeiter B|
:Verständnis
sicherstellen;
:bereit}
:ruhend.../
:umsetzung}
:Lösung erarbeiten;
:Lösung intern
prüfen (lassen);
:Lösung abnehmen
lassen;
:abgeschlossen}
end
@enduml