@startuml
|AGI-Mitarbeiter|

:umsetzung}

:Arbeiten
planen;

:zu Rollout
zuweisen;

if (DDL?) then (nein)
  :Änderungen
  umsetzen;
  :Anpassung intern
  prüfen (lassen);
  :Anpassung durch
  Ticket-Ersteller
  abnehmen (lassen);
  :abgeschlossen}
  stop
else (ja)
  :DDL erarbeiten;
  :DDL durch Admin
  auf Integration
  ausführen lassen;

endif

:Änderungen
umsetzen;

:Anpassung intern
prüfen (lassen);
:Anpassung durch
Ticket-Ersteller
abnehmen lassen;
:rollout-ready}

:Layer-Rollout
abwarten ...;

:Auf Prod
prüfen;
:abgeschlossen}

end
@enduml