@startuml
|Mitarbeiter Fachamt|
start
:Feststellung
verschriftlichen
(lassen);
|GIS-Koordinator|
:Ticket eröffnen;
:entwurf}
|Ticket-Triage|
if (Geodaten
bezogen?) then (nein)
  if (FE-bezogen?) then (ja)
    :An Anwendungs-
    Verantwortlichen
    zuweisen;
    stop
    note right
    	(1)
    end note
  else (nein)
    :An GDI-
    Koordinator
    zuweisen;
    stop
    note right
    	(1)
    end note
  endif
else (ja)
  :mit SPOC
  besprechen;
  if (bleibt Tages-
  geschäft?) then (ja)
    :bereit}
    :An AGI-
    Mitarbeiter
    zuweisen;
    stop
    note right
    	(2)
    end note
  else (nein)
    |Ticket-Triage|
  	:An SPOC
    zuweisen;
    stop
    note right
    	(1)
    end note
  endif
endif
legend left
  (1): Weiter mit Basisablauf, Mitarbeiter B
  (2): Weiter mit "Ablauf für Layer-Rollout-Ticket"
end legend
@enduml