@startuml
legend top
	Ablauf eines Auftrages
end legend

|GIS-Koordinator|
start
:Auftrags-Ticket
erstellen;
:entwurf}
:WAS-Teil zu
Auftrag erfassen;
|SPOC|
:WIE-Erarbeitung
organisieren;
|AGI-Mitarbeiter|
:WIE-Teil
erarbeiten;
:Umsetzung durch SPOC
freigeben lassen;
:bereit}
:umsetzung}
:Umsetzen;
:Durch GIS-Koordinator
abnehmen lassen;
:abgeschlossen}
end
@enduml