@startuml
|Mitarbeiter Fachamt|
start
:Feststellung
verschriftlichen
(lassen);
|GIS-Koordinator|
:Ticket eröffnen;
:entwurf}
|Ticket-Triage|
if (Geodaten
bezogen?) then (nein)
  if (FE-bezogen?) then (ja)
    :An Anwendungs-
    Verantwortlichen
    zuweisen;
    stop
    note right
    	(TG, DEV)
    end note
  else (nein)
    :An GDI-
    Koordinator
    zuweisen;
    stop
    note right
    	(TG)
    end note
  endif
else (ja)
  :mit SPOC
  besprechen;
  if (bleibt Tages-
  geschäft?) then (ja)
    :bereit}
    :An AGI-
    Mitarbeiter
    zuweisen;
    stop
    note right
    	(ROLL)
    end note
  else (nein)
    |Ticket-Triage|
  	:An SPOC
    zuweisen;
    stop
    note right
    	(AUF, PRJ)
    end note
  endif
endif
legend left
  (TG): 	Tagesgeschäft
  (DEV):	Software-Entwicklungsarbeit
  (AUF):	Auftrag
  (PRJ):	Projekt
  (ROLL):	Rollout-Geschäft
end legend
@enduml