@startuml
left to right direction

:Chefe mit\nAmtsleitung: as chef
:Betriebs-\nVerantwortlicher: as bv
:Anwendungs-\nVerantwortlicher: as av
:AGI-Betrieb: as betrieb

(Projekt priorisieren\n-Siehe Projekte und Aufträge) as pprio

(Betriebsanforderung\npriorisieren) as runtick
(Endanwenderanforderung\ndefinieren / priorisieren) as usertick
(Release als Projekt\nbeantragen) as release
(Projekt initialisieren\n-Siehe Projekte und Aufträge) as init
(Releasegebundene\nAnpassung definieren) as rtick
(Ungebundene Anpassung /\nStörung definieren) as tick



chef --> pprio

bv --> runtick
av --> usertick
av --> release
av --> init

betrieb --> rtick
betrieb --> tick
@enduml