@startuml
legend top
	Ablauf eines AGI internen Projektes
end legend
|AGI-Mitarbeiter|
start
:Projektidee mit
Chef besprechen;
:idee}
|AL|
:Projekt priorisieren
(Halbjärlich);
|PL|
:Init-Meeting
durchfüren;
:...
ab hier
Gleich wie bei
GIS-Projekt
...;
end
@enduml