@startuml
legend top
	AGI-relevante Ablaufteile eines Trio-Projektes
end legend
|AG|
start
:Projekt bei
IV anmelden;
|IV / GIS-Koordinator|
:Projekt bei
SPOC anmelden;
|SPOC / AGI PA|
:entwurf}
:Varianten-
entscheid
unterstützen;
:bereit}
:initialisierung}
:AGI-Arbeiten
strukturieren;
:AGI-Arbeiten
mit PL vereinbaren;
:konzept}
:Konzept-
AP's erarbeiten
(lassen);
:Pflichtenheft
für Ausschreibung
freigeben;
:Auftragsvergabe
freigeben;
|AGI-Mitarbeiter|
:realisierung}
:Realisierungs-
AP's erarbeiten;
:einführung}
:Einführungs-
AP's erarbeiten;
:abgeschlossen}
end
@enduml