@startuml
legend top
	Ablauf eines Auftrages
end legend

|GIS-Koordinator|
start
:Auftrags-Ticket
erstellen;
:entwurf}
:WAS-Teil zu
Auftrag erfassen;
|SPOC|
:WIE-Erarbeitung
organisieren;
|AGI-Mitarbeiter|
:WIE-Teil
erarbeiten;
|SPOC|
:bereit}
:Umsetzung
freigeben;
:umsetzung}
|AGI-Mitarbeiter|
:Umsetzen;
|GIS-Koordinator|
:Abnehmen;
:abgeschlossen}
end
@enduml