@startuml
legend top
	Ablauf eines GIS-Projektes
end legend
|AG|
start
:Projekt bei
IV anmelden;
|IV / GIS-Koordinator|
:Projekt bei
SPOC anmelden;
|SPOC|
:entwurf}
|AG|
:PMP Kapitel 1
erarbeiten
(lassen);
|SPOC|
:Projekt in
AL geben zwecks
Priorisierung
(Halbjährlich);
|PL|
:Init-Meeting
durchführen;
:initialisierung}
:PMP für
Konzeptphase
erarbeiten;
:Phasenübergang
bei AG beantragen;
:Kickoff-Meetings
durchfüren;
|AG|
:Projekt freigeben;
|PL|
:konzept}
:Konzept AP's
erarbeiten (lassen);
:PMP für
Realisierung
erarbeiten;
:Phasenübergang
bei AG beantragen;
|AG|
:Realisierung
freigeben;
|PL|
:realisierung}
:Realisierung's AP's
erarbeiten (lassen);
:PMP für
Einführung
erarbeiten;
:Phasenübergang
bei AG beantragen;
|AG|
:Einführung
freigeben;
|PL|
:einführung}
:Einführungs's AP's
erarbeiten (lassen);
:PMP für
Projektabschluss
erarbeiten;
:Projektabschluss
bei AG beantragen;
|AG|
:Projektabschluss
bewilligen;
|PL|
:abgeschlossen}
end
@enduml