@startuml
legend top
	Ablauf eines Rollout-Tickets
end legend
|Ticket-Triage|
start
:Verantwortlichen
bestimmen;
|AGI-Mitarbeiter|

:umsetzung}

:Arbeiten
planen;

if (DDL?) then (nein)

else (ja)

:Betrieb mit
DDL-Kindticket
beauftragen;

|AGI-Betrieb|

:DDL
erarbeiten;

endif

|AGI-Mitarbeiter|

:Nicht-DDL
Änderungen
erarbeiten;

:Anpassungen
bestätigen
lassen;

:zu Rollout
zuweisen;

|AGI-Betrieb|
:Layer-Rollout
durchführen;

:abgeschlossen}

end
@enduml