@startuml
legend top
	Ablauf eines AGI internen Projektes
end legend
|AGI-Mitarbeiter|
start
:Projektidee mit
Chef besprechen;
:entwurf}
|AL|
:Projekt priorisieren
(Halbjärlich);
:bereit}
|PL|
:Init-Meeting
durchfüren;
:initialisierung}
:
Ab hier
gleicher
Ablauf
wie bei
GIS-Projekt
...;
end
@enduml